language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.pip
  - pip install -q -e .
before_script:
   - mkdir -p shippable/testresults
   - mkdir -p shippable/codecoverage
script:
  - python manage.py test
